name: Publish assets

on:
  release:
    types:
      - published

jobs:
  publish-assets:
    runs-on: ubuntu-latest

    env:
      DIST_DIR: ./dist
      PUBLISH_BRANCH: gh-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Build catalog
        uses: cloud-native-toolkit/action-module-metadata-create@v1
        with:
          tagName: ${{ github.event.release.tag_name }}
          distDir: ${{ env.DIST_DIR }}
          publishBranch: ${{ env.PUBLISH_BRANCH }}
          strict: false
          validate: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.DIST_DIR }}
          publish_branch: ${{ env.PUBLISH_BRANCH }}
